---
- name: Ensure 'make' is installed on the server
  apt:
    name: make
    state: present

- name: Copy Inception folder to the VM
  copy:
    src: ./Inception
    dest: "/home/{{ ansible_user }}/"
    owner: "{{ ansible_user }}"
    mode: '0755'

- name: Generate .env file (Ansible manages your secrets)
  template:
    src: .env.j2
    dest: "/home/{{ ansible_user }}/Inception/srcs/.env"

- name: Run the Inception Makefile
  community.general.make:
    chdir: "/home/{{ ansible_user }}/Inception"
    target: all