services:
  mysql:
    build: ./requirements/mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    container_name: "mysql"
    env_file:
      - ./.env
    restart: always

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wpdata:/var/www/html
    networks:
      - app-network
    container_name: "wordpress"
    depends_on:
      - mysql
    env_file:
      - ./.env
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin"
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      PMA_ABSOLUTE_URI: https://hnaciri-maamer.duckdns.org/phpmyadmin/ 
    networks:
      - app-network
    depends_on:
      - mysql

  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wpdata:/var/www/html
    networks:
      - app-network
    depends_on:
      - wordpress
      - phpmyadmin
    container_name: "nginx"
    restart: always

volumes:
  dbdata:
    driver: local
    driver_opts:
      device: ${DATA_PATH}/mysql
      type: "none"
      o: bind
  wpdata:
    driver: local
    driver_opts:
      device: ${DATA_PATH}/wordpress
      type: "none"
      o: bind

networks:
  app-network:
    driver: bridge