---
- name: Update apt and install base packages
  apt:
    update_cache: yes
    name:
      - ufw
      - curl
      - git
      - python3-pip
      - ca-certificates
    state: present

- name: Allow SSH traffic
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Allow HTTP traffic
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow HTTPS traffic
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Enable UFW and set default deny policy
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming
